# Magisim docker container setup (NOT READY FOR USE)

# pull base image
FROM ubuntu:18.04

# install miniconda
RUN apt-get update && apt-get install -y wget bzip2 git 
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
RUN bash Miniconda3-latest-Linux-x86_64.sh -b
RUN rm Miniconda3-latest-Linux-x86_64.sh
ENV PATH="/root/miniconda3/bin:${PATH}"
RUN conda init
# clone latest magisim release
RUN wget https://github.com/devbrones/magisim/releases/latest/magisim.tar.gz
RUN tar -xvf magisim.tar.gz
RUN rm magisim.tar.gz
RUN cd magisim
RUN conda env create -f environment.yml
RUN conda activate magisim
# install custom magisim fdtd library
RUN mkdir local
RUN cd local
RUN git clone https://github.com/devbrones/fdtd
RUN pip3 install -e ./fdtd
RUN cd ..
