remote_theme: "mmistakes/minimal-mistakes@4.24.0" 
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme
  - jekyll-include-cache

minimal_mistakes_skin: "dark"

title: Magisim
description: Democratizing intuitive computation
show_downloads: false
github:
  zip_url: https://cdn.magisim.com/eu-se1/core/latest.zip
  tar_url: https://cdn.magisim.com/eu-se1/core/latest.tar.gz

